import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import {
  LOGO_COLORS, LOGO_PATHS, RULE_STROKE, RUPEE_SCALE, RUPEE_STROKE, RUPEE_TRANSLATE,
  STEM_STROKE, logoSvg,
} from '../src/components/logoArt.ts'

/**
 * Regenerate every copy of the mark from `src/components/logoArt.ts`.
 *
 *   npm run icons
 *
 * The favicon and the two Android vector drawables are build outputs, not
 * artwork. They are committed because the Android build needs them on disk,
 * but nothing should ever be edited in place — change logoArt.ts and run this.
 * Before it existed the launcher icon and the app header drifted apart within
 * a week, because four files held four copies of the same paths.
 */

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const res = join(root, 'android', 'app', 'src', 'main', 'res')

const GENERATED = 'GENERATED by scripts/icons.mjs from src/components/logoArt.ts — do not edit.'

/**
 * The 64x64 artwork inside Android's 108x108 adaptive viewport.
 *
 * A group transform rather than rewritten coordinates: the launcher masks
 * anything outside the central safe zone, and `scale 1.125, translate 18`
 * lands the 64 box exactly inside it. Android applies scale before translate,
 * which is the order this relies on. Stroke widths inside the group are scaled
 * with it, so they stay in the artwork's own units here too.
 */
const openGroup = '    <group android:scaleX="1.125" android:scaleY="1.125" android:translateX="18" android:translateY="18">'

function vector(body) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${openGroup}
${body}
    </group>
</vector>
`
}

const fill = (d, color) =>
  `        <path\n            android:fillColor="${color}"\n            android:pathData="${d}" />`

const stroke = (d, color, width, cap = 'round') =>
  `        <path\n            android:strokeColor="${color}"\n            android:strokeWidth="${width}"\n            android:strokeLineCap="${cap}"\n            android:strokeLineJoin="round"\n            android:pathData="${d}" />`

/* ------------------------------------------------------------------ *
 * Adaptive-icon foreground — the full-colour mark, no tile
 * ------------------------------------------------------------------ */

const foreground = vector(
  [
    fill(LOGO_PATHS.coverLeft, LOGO_COLORS.cover),
    fill(LOGO_PATHS.coverRight, LOGO_COLORS.coverShade),
    fill(LOGO_PATHS.pageLeft, LOGO_COLORS.page),
    fill(LOGO_PATHS.pageRight, LOGO_COLORS.pageShade),
    stroke(LOGO_PATHS.rules, LOGO_COLORS.rule, RULE_STROKE),
    stroke(LOGO_PATHS.stem, LOGO_COLORS.stem, STEM_STROKE),
    fill(LOGO_PATHS.leafBack, LOGO_COLORS.leafBack),
    fill(LOGO_PATHS.leafFront, LOGO_COLORS.leafFront),
    fill(LOGO_PATHS.coin, LOGO_COLORS.coin),
    // The rupee gets its own nested group: it is authored in a 24x24 box.
    `        <group android:scaleX="${RUPEE_SCALE}" android:scaleY="${RUPEE_SCALE}" android:translateX="${RUPEE_TRANSLATE.x}" android:translateY="${RUPEE_TRANSLATE.y}">
${stroke(LOGO_PATHS.rupee, LOGO_COLORS.ink, RUPEE_STROKE)}
        </group>`,
  ].join('\n'),
)

/* ------------------------------------------------------------------ *
 * Themed-icon layer for Android 13+
 * ------------------------------------------------------------------ */

/*
 * The system ignores the colours here and uses only the shape, tinting it to
 * match the launcher's wallpaper theme. So this is the same artwork as one
 * solid silhouette: the page shading, the ruled lines and the rupee would all
 * be invisible once flattened, and an invisible seam looks worse than a shape
 * that was never drawn.
 */
const BLACK = '#000000'
const monochrome = vector(
  [
    fill(LOGO_PATHS.coverLeft, BLACK),
    fill(LOGO_PATHS.coverRight, BLACK),
    stroke(LOGO_PATHS.stem, BLACK, STEM_STROKE),
    fill(LOGO_PATHS.leafBack, BLACK),
    fill(LOGO_PATHS.leafFront, BLACK),
  ].join('\n'),
)

/* ------------------------------------------------------------------ */

const written = [
  [join(root, 'public', 'logo.svg'), logoSvg({ size: 64 })],
  [join(res, 'drawable-v24', 'ic_launcher_foreground.xml'), foreground],
  [join(res, 'drawable', 'ic_launcher_monochrome.xml'), monochrome],
]

for (const [path, contents] of written) {
  writeFileSync(path, contents, 'utf8')
  console.log('wrote', path.slice(root.length + 1))
}
